export const calles = [
    "San Martín",
    "Belgrano",
    "Rivadavia",
    "Sarmiento",
    "Independencia",
    "25 de Mayo",
    "Mitre",
    "Pueyrredón",
    "Alberdi",
    "Moreno",
    "Alsina",
    "Urquiza",
    "Lavalle",
    "San Juan",
    "San Luis",
    "Santa Fe",
    "Córdoba",
    "Entre Ríos",
    "Salta",
    "La Rioja",
    "Corrientes",
    "Mendoza",
    "Tucumán",
    "Jujuy",
    "Catamarca",
    "Chaco",
    "Formosa",
    "Neuquén",
    "Santa Cruz",
    "Tierra del Fuego",
    "Chubut",
    "La Pampa",
    "San Juan",
    "San Luis",
    "La Plata",
    "General Paz",
    "Avenida de Mayo",
    "9 de Julio",
    "Callao",
    "Cabildo",
    "Alem",
    "Cerrito",
    "Florida",
    "Suipacha",
    "Diagonal Norte",
    "Diagonal Sur",
    "Carlos Pellegrini",
    "Santa María",
    "Piedras",
    "Perú",
    "Humberto Primo",
    "Saavedra",
    "Bolívar",
    "Tacuarí",
    "Carlos Calvo",
    "San José",
    "Defensa",
    "Alsina",
    "Balcarce",
    "Hipólito Yrigoyen",
    "Lima",
    "Santiago del Estero",
    "San Cristóbal",
    "Combate de los Pozos",
    "Av. de los Constituyentes",
    "Av. Corrientes",
    "Av. Córdoba",
    "Av. Scalabrini Ortiz",
    "Av. Juan B. Justo",
    "Av. Rivadavia",
    "Av. Santa Fe",
    "Av. Callao",
    "Av. San Juan",
    "Av. Independencia",
    "Av. La Plata",
    "Av. Belgrano",
    "Av. Pueyrredón",
    "Av. Congreso",
    "Av. Cabildo",
    "Av. Alberdi",
    "Av. San Martín",
    "Av. Mitre",
    "Av. 9 de Julio",
    "Av. Perú",
    "Av. Brasil",
    "Av. San Lorenzo",
    "Av. San Martín",
    "Av. De los Incas",
    "Av. Monroe",
    "Av. Triunvirato",
    "Av. Álvarez Jonte",
    "Av. Gaona",
    "Av. Lope de Vega",
    "Av. Nazca",
    "Av. Segurola",
    "Av. Directorio",
    "Av. Rivadavia",
    "Av. Juan Bautista Alberdi",
    "Av. San Pedrito",
]